spring:
  datasource:
    password: 1234
    url: jdbc:mysql://localhost:3306/queueplay
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: queueplay
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        alect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: false
        show_sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
